package com.rai.kurdmessenger.InDeCrypter;

/**
 * Created by alex on 01/01/2009.
 */

public class DeCrypte {

    public static char decrypte(char c){

        switch (c) {
            case 'ی':  c ='a';
                break;
            case 'ا':  c = 'b';
                break;
            case 'a':  c = 'c';
                break;
            case 'ه':  c = 'd';
                break;
            case 'آ':  c ='e';
                break;
            case 'b':  c = 'f';
                break;
            case 'و':  c = 'g';
                break;
            case 'ب':  c = 'h';
                break;
            case 'c':  c = 'i';
                break;
            case 'ن': c = 'j';
                break;
            case 'س': c = 'k';
                break;
            case 'd': c = 'l';
                break;
            case 'م':  c = 'm';
                break;
            case 'ث':  c = 'n';
                break;
            case 'e':  c = 'o';
                break;
            case 'r':  c = 'p';
                break;
            case 'ج':  c = 'q';
                break;
            case 'p':  c = 'r';
                break;
            case 'گ':  c = 's';
                break;
            case 'چ':  c = 't';
                break;
            case 'g':  c = 'u';
                break;
            case 'ک': c = 'v';
                break;
            case 'ح': c = 'w';
                break;
            case 'h': c = 'x';
                break;
            case 'ق':  c = 'y';
                break;
            case 'خ':  c = 'z';
                break;
            case 'i':  c = 'A';
                break;
            case 'ف':  c = 'B';
                break;
            case 'د':  c = 'C';
                break;
            case 'j':  c = 'D';
                break;
            case 'غ':  c = 'E';
                break;
            case 'ذ':  c = 'F';
                break;
            case 'k':  c = 'G';
                break;
            case 'ع':  c = 'H';
                break;
            case 'U':  c = 'I';
                break;
            case 'l': c = 'J';
                break;
            case 'ظ': c = 'K';
                break;
            case 'ز': c = 'L';
                break;
            case 'm':  c = 'M';
                break;
            case 'ط':  c = 'N';
                break;
            case 'ژ':  c = 'O';
                break;
            case 'R':  c = 'P';
                break;
            case 'ض':  c = 'Q';
                break;
            case 'P':  c = 'R';
                break;
            case 'o':  c = 'S';
                break;
            case 'ص':  c = 'T';
                break;
            case 'ش':  c = 'U';
                break;
            case 'f': c = 'V';
                break;
            case 'Z': c = 'W';
                break;
            case 'Y': c = 'X';
                break;
            case 'ل':  c = 'Y';
                break;
            case 'X':  c = 'Z';
                break;
            case 'W':  c ='ا';
                break;
            case 's':  c = 'آ';
                break;
            case 'V':  c = 'ب';
                break;
            case 'ر':  c = 'پ';
                break;
            case 't':  c = 'ث';
                break;
            case 'T':  c = 'ج';
                break;
            case 'S':  c = 'چ';
                break;
            case 'u':  c = 'ح';
                break;
            case 'n':  c = 'خ';
                break;
            case 'Q': c = 'د';
                break;
            case 'v': c = 'ذ';
                break;
            case 'پ': c = 'ر';
                break;
            case 'O':  c = 'ز';
                break;
            case 'w':  c = 'ژ';
                break;
            case 'N':  c = 'س';
                break;
            case 'M':  c = 'ش';
                break;
            case 'x':  c = 'ص';
                break;
            case 'L':  c = 'ض';
                break;
            case 'K':  c = 'ط';
                break;
            case 'y':  c = 'ظ';
                break;
            case 'J':  c = 'ع';
                break;
            case 'I': c = 'غ';
                break;
            case 'z': c = 'ف';
                break;
            case 'H': c = 'ق';
                break;
            case 'G':  c = 'ک';
                break;
            case 'F':  c = 'گ';
                break;
            case 'E':  c = 'ل';
                break;
            case 'D':  c = 'م';
                break;
            case 'C':  c = 'ن';
                break;
            case 'B':  c = 'و';
                break;
            case 'A':  c = 'ه';
                break;
            case 'q':  c = 'ی';
                break;
            default: c = c;
                break;
        }

        return c;
    }
}
